const Sdata=[
    {   
           id:1,
            imgsrc:"https://wallpapercave.com/w/wp3198150.jpg",
            title:"Hotstar Premium",
            sname:"Iron Man",
            link:" https://www.hotstar.com/in/movies/iron-man/1660000038 ",
            wiki:"https://en.wikipedia.org/wiki/Iron_Man_(2008_film)",
    },
    {
        id:2,
        imgsrc:"https://wallpapercave.com/w/9ESM4OY.jpg",
            title:"Hotstar Premium",
            sname:'Iron Man 2',
            link:" https://www.hotstar.com/in/movies/iron-man-2/1660000039",
            wiki:"https://en.wikipedia.org/wiki/Iron_Man_2",
    },
    {
        id:3,
        imgsrc:"https://wallpapercave.com/w/wp1886660.jpg",
        title:"Hotstar Premium",
        sname:'Iron Man 3',
        link:" https://www.hotstar.com/in/movies/iron-man-3/1660000042",
        wiki:"https://en.wikipedia.org/wiki/Iron_Man_2"
    },
    {   id:4,
        imgsrc:"https://wallpapercave.com/w/HYqSmag.jpg",
        title:"Hotstar Premium",
        sname:'Thor',
        link:"https://www.hotstar.com/in/movies/thor/1660000044",
        wiki:"https://en.wikipedia.org/wiki/Thor_(film)",
    },
    {   id:5,
        imgsrc:"https://wallpapercave.com/w/wp3775630.jpg",
        title:"Hotstar Premium",
        sname:'Captain America:The First Avenger',
        link:" https://www.hotstar.com/in/movies/captain-america-the-first-avenger/1660000034",
        wiki:"https://en.wikipedia.org/wiki/Captain_America:_The_First_Avenger",
    },
    {
        id:6,
        imgsrc:"https://wallpapercave.com/w/wp3079588.jpg",
        title:"Hotstar Premium",
        sname:'Thor:Dark World',
        link:"https://www.hotstar.com/in/movies/thor-the-dark-world/1260018142",
        wiki:"https://en.wikipedia.org/wiki/Captain_America:_The_Winter_Soldier",
    },
    {
        id:7,
        imgsrc:"https://wallpapercave.com/w/wp1820128.jpg",
        title:"Hotstar Premium",
        sname:'Captain America: 2',
        link:" https://www.hotstar.com/in/movies/captain-america-the-winter-soldier/1260016410",
        wiki:"https://en.wikipedia.org/wiki/The_Incredible_Hulk_(film)",
    },
    {
        id:8,
        imgsrc:"https://wallpapercave.com/w/wp1814934.jpg",
        title:"Hotstar Premium",
        sname:'Guardians of Galaxy',
        link:"https://www.hotstar.com/in/movies/guardians-of-the-galaxy/1260018294",
        wiki:"https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(film)",
    },
    {
        id:9,
        imgsrc:"https://wallpapercave.com/w/wp1833134.jpg",
        title:"Hotstar Premium",
        sname:'Avengers:Age of Ultron',
        link:" https://www.hotstar.com/in/movies/marvels-avengers-age-of-ultron/1260018315",
        wiki:"https://en.wikipedia.org/wiki/Avengers:_Age_of_Ultron",
    },
    {
        id:10,
        imgsrc:"https://wallpapercave.com/w/wp1810494.jpg",
        title:"Hotstar Premium",
        sname:'Ant-Man',
        link:"hotstar.com/in/movies/antman/1260018141 ",
        wiki:"https://en.wikipedia.org/wiki/Ant-Man_(film)",
    },
    {
        id:11,
        imgsrc:"https://wallpapercave.com/w/wp2028630.jpg",
        title:"Hotstar Premium",
        sname:'Doctor Strange',
        link:"https://www.hotstar.com/in/movies/doctor-strange/1260018179 ",
        wiki:"https://en.wikipedia.org/wiki/Doctor_Strange_(2016_film)",
    },
    {
        id:12,
        imgsrc:"https://wallpapercave.com/w/wp1869905.jpg",
        title:"Hotstar Premium",
        sname:'Black Panther',
        link:"https://www.hotstar.com/in/movies/black-panther/1660010672",
        wiki:"https://en.wikipedia.org/wiki/Black_Panther_(film)",
    },
    {
        id:13,
        imgsrc:"https://wallpapercave.com/w/wp2207620.jpg",
        title:"Hotstar Premium",
        sname:'X-Men',
        link:"https://www.hotstar.com/in/movies/xmen/1770000943",
        wiki:"https://en.wikipedia.org/wiki/X-Men_(film)",
    },
    {
        id:14,
        imgsrc:"https://wallpapercave.com/w/wp6989192.jpg",
        title:"Hotstar Premium",
        sname:'X-Men 2',
        link:"https://www.hotstar.com/in/movies/xmen-united/1770000775",
        wiki:"https://en.wikipedia.org/wiki/X2_(film)",
    },
    {
        id:15,
        imgsrc:"https://wallpapercave.com/w/wp5271929.jpg",
        title:"Hotstar Premium",
        sname:'X-Men:The Last Stand',
        link:"https://www.hotstar.com/in/movies/xmen-the-last-stand/1770000804",
        wiki:"https://en.wikipedia.org/wiki/X-Men:_The_Last_Stand",
    },
    {
        id:16,
        imgsrc:"https://wallpapercave.com/w/wp2033177.jpg",
        title:"Hotstar Premium",
        sname:'Guardians of the Galaxy Vol. 2',
        link:"https://www.hotstar.com/in/movies/guardians-of-the-galaxy-vol-2/1260018295",
        wiki:"https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_Vol._2",
    },
    {
        id:17,
        imgsrc:"https://wallpapercave.com/w/wp3892152.jpg",
        title:"Hotstar Premium",
        sname:'Captain Marvel',
        link:"https://www.hotstar.com/in/movies/captain-marvel/1260014878",
        wiki:"https://en.wikipedia.org/wiki/Captain_Marvel_(film)",
    },
    {
        id:18,
        imgsrc:"https://wallpapercave.com/w/wp2345889.jpg",
        title:"Hotstar Premium",
        sname:'Thor:Ragnarok',
        link:"https://www.hotstar.com/in/movies/thor-ragnarok/1660010577",
        wiki:"https://en.wikipedia.org/wiki/Thor:_Ragnarok",
    },
    {
        id:19,
        imgsrc:"https://wallpapercave.com/w/wp1809485.jpg",
        title:"Hotstar Premium",
        sname:'Captain America: Civil War',
        link:"https://www.hotstar.com/in/movies/captain-america-civil-war/1260016768",
        wiki:"https://en.wikipedia.org/wiki/Captain_America:_Civil_War",
    },

    {
        id:20,
        imgsrc:"https://wallpapercave.com/w/6lvp4zT.jpg",
        title:"Hotstar Premium",
        sname:"Marvel's The Avengers",
        link:"https://www.hotstar.com/in/movies/marvels-the-avengers/1660000015",
        wiki:"https://en.wikipedia.org/wiki/The_Avengers_(2012_film)",
    },
    {
        id:21,
        imgsrc:"https://wallpapercave.com/w/wp2049903.jpg",
        title:"Hotstar Premium",
        sname:"Avengers: Infinity War ",
        link:"https://www.hotstar.com/in/movies/avengers-infinity-war/1660010677",
        wiki:"https://en.wikipedia.org/wiki/Avengers:_Infinity_War",
    },
    {
        id:22,
        imgsrc:"https://wallpapercave.com/w/wp3850252.jpg",
        title:"Hotstar Premium",
        sname:"Avengers: Endgame",
        link:"https://www.hotstar.com/in/movies/avengers-endgame/1260013556",
        wiki:"https://en.wikipedia.org/wiki/Avengers:_Endgame",
    },
    { 
        id:23,
        imgsrc:"https://wallpapercave.com/w/wp1962460.jpg",
        title:"Hotstar Premium",
        sname:"X-Men Origins: Wolverine",
        link:"https://www.hotstar.com/in/movies/xmen-origins-wolverine/1770000667",
        wiki:"https://en.wikipedia.org/wiki/X-Men_Origins:_Wolverine",
    },
    {
        id:24,
        imgsrc:"https://wallpapercave.com/w/H7dqSZ9.jpg",
        title:"Hotstar Premium",
        sname:"The Wolverine",
        link:"https://www.hotstar.com/in/movies/avengers-infinity-war/1660010677",
        wiki:"https://en.wikipedia.org/wiki/The_Wolverine_(film)",
    },
    {
        id:25,
        imgsrc:"https://wallpapercave.com/w/wp1962466.jpg",
        title:"Hotstar Premium",
        sname:"Logan",
        link:"https://www.hotstar.com/in/movies/logan/1770016994",
        wiki:"https://en.wikipedia.org/wiki/Logan_(film)",
    },
    {
        id:26,
        imgsrc:"https://wallpapercave.com/w/wp5271905.jpg",
        title:"Hotstar Premium",
        sname:"X-Men: First Class",
        link:"https://www.hotstar.com/in/movies/xmen-first-class/1770000666",
        wiki:"https://en.wikipedia.org/wiki/X-Men:_First_Class",
    },
    {
        id:27,
        imgsrc:"https://wallpapercave.com/w/wp2420809.jpg",
        title:"Hotstar Premium",
        sname:"X-Men: Days of Future Past",
        link:"https://www.hotstar.com/in/movies/xmen-days-of-future-past/1770000446",
        wiki:"https://en.wikipedia.org/wiki/X-Men:_Days_of_Future_Past",
    },
    {
        id:28,
        imgsrc:"https://wallpapercave.com/w/wp2009455.jpg",
        title:"Hotstar Premium",
        sname:"X-Men: Apocalypse",
        link:"https://www.hotstar.com/in/movies/xmen-apocalypse/1770015391/watch",
        wiki:"https://en.wikipedia.org/wiki/X-Men:_Apocalypse",
    },
    {
        id:29,
        imgsrc:"https://wallpapercave.com/w/wp4031146.jpg",
        title:"Hotstar Premium",
        sname:"Dark Phoenix",
        link:"https://www.hotstar.com/in/movies/xmen-apocalypse/1770015391/watch",
        wiki:"https://en.wikipedia.org/wiki/Dark_Phoenix_(film)",
    },
    {
        id:30,
        imgsrc:"https://wallpapercave.com/w/wp2550892.jpg",
        title:"Hotstar Premium",
        sname:"Deadpool",
        link:"https://www.hotstar.com/in/movies/deadpool/1770003257",
        wiki:"https://en.wikipedia.org/wiki/Deadpool_(film)",
    },
    {
        id:31,
        imgsrc:"https://wallpapercave.com/w/wp2377673.jpg",
        title:"Hotstar Premium",
        sname:"Deadpool 2",
        link:"https://www.hotstar.com/in/movies/deadpool-2/1770020234",
        wiki:"https://en.wikipedia.org/wiki/Deadpool_2",
    },
    {
        id:32,
        imgsrc:"https://wallpapercave.com/w/kciudSr.jpg",
        title:"Hotstar Premium",
        sname:"Black Widow",
        link:"https://www.hotstar.com/in/movies/black-widow/1260067485",
        wiki:"https://en.wikipedia.org/wiki/Black_Widow_(2021_film)",
    },
    {
        id:33,
        imgsrc:"https://wallpapercave.com/w/wp8753880.jpg",
        title:"Hotstar Premium",
        sname:"Shang-Chi and the Legend of the Ten Rings",
        link:"https://www.youtube.com/watch?v=giWIr7U1deA",
        wiki:"https://en.wikipedia.org/wiki/Shang-Chi_and_the_Legend_of_the_Ten_Rings",
    },
    {
        id:34,
        imgsrc:"https://wallpapercave.com/w/wp8753880.jpg",
        title:"Hotstar Premium",
        sname:"Shang-Chi and the Legend of the Ten Rings",
        link:"https://www.youtube.com/watch?v=giWIr7U1deA",
        wiki:"https://en.wikipedia.org/wiki/Shang-Chi_and_the_Legend_of_the_Ten_Rings",
    },
    {
        id:35,
        imgsrc:"https://wallpapercave.com/w/wp8116312.jpg",
        title:"Hotstar Premium",
        sname:"Loki",
        link:"https://www.hotstar.com/in/tv/loki/1260064562",
        wiki:"https://en.wikipedia.org/wiki/Loki_(Marvel_Cinematic_Universe)",
    },
    {
        id:36,
        imgsrc:"https://wallpapercave.com/w/wp7089368.jpg",
        title:"Hotstar Premium",
        sname:"The New Mutants ",
        link:"https://www.hotstar.com/in/movies/the-new-mutants/1260057812",
        wiki:"https://en.wikipedia.org/wiki/The_New_Mutants_(film)",
    },  
    {
        id:37,
        imgsrc:"https://wallpapercave.com/w/wp1908901.jpg",
        title:"Hotstar Premium",
        sname:"Spider Man:Homecoming",
        link:"https://www.youtube.com/watch?v=n9DwoQ7HWvI",
        wiki:"https://en.wikipedia.org/wiki/Spider-Man:_Homecoming",
    },   
    {
        id:38,
        imgsrc:"https://wallpapercave.com/w/wp8651516.jpg",
        title:"Hotstar Premium",
        sname:"Spider Man:No way Home",
        link:"https://www.youtube.com/watch?v=rt-2cxAiPJk",
        wiki:"https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home",
    },  
];
export default Sdata;